#!/usr/bin/env php

<?php

define( 'TIGA_INSTANCE', 'tigaaisthemesapi' );

require __DIR__ . '/../tiga/app/bootstrap.php';
require __DIR__ . '/app/bootstrap.php';

$console = require "../tiga/tiga-command.php";

$console->run();